Hotfix/develop restructure
PLTCom/PLT-org pull request #16
Opened 2020-03-10 03:31 UTC by logicpriest

2020-03-10 14:16 UTC, Joedirte1917 approved these changes

2020-03-11 01:01 UTC, 1bigchonk requested changes

2020-03-11 01:01 UTC, 1bigchonk commented on docs/modules/member-expectations.adoc
>  Committee or Working Group meetings should be held monthly, at a minimum. Members need to attend 75% of committee or working group meetings held during a year to remain a full member. If this is not
```suggestion
Committee or Working Group meetings should be held monthly, at a minimum. Members need to attend 75% of committee or working group meetings held during a year to remain a full member. If this is not met, member status will revert to provisional status.
```

2020-03-14 00:06 UTC, 1bigchonk approved these changes

2020-03-14 00:06 UTC, merged